package edu.kent.babelpages.rest.books;

import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.UUID;

/**
 * Important note on how Books are stored:
 * We use a comma separated string for multiple authors
 */
@Repository
public class BooksDAO {
    private static String BUILD_QUERY_SELECT_SEARCH(String orderByColumn) {
        return "SELECT * FROM books ORDER BY " + orderByColumn + " LIMIT ? OFFSET ?";
    }

    private static String BUILD_QUERY_SELECT_SEARCH_WITH_KEYWORD(String orderByColumn) {
        return "SELECT * FROM books " +
                "WHERE title LIKE :keyword OR authors LIKE :keyword ORDER BY "
                + orderByColumn + " LIMIT :limit OFFSET :offset";
    }

    private final String SQL_SELECT_BY_ID = "SELECT * FROM books WHERE id = ?";
    private final String SQL_INSERT_BOOK = "INSERT INTO books " +
            "(id, title, description, isbn, language, price, stock_quantity, authors, cover_url, pub_year, pub_month, pub_day)" +
            " VALUES (?, ?, ?, ?, ?, ?, ? ,?, ?, ?, ?, ?)";

    private final JdbcTemplate jdbcTemplate;
    private final NamedParameterJdbcTemplate namedParameterJdbcTemplate;

    public BooksDAO(JdbcTemplate jdbcTemplate, NamedParameterJdbcTemplate namedParameterJdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.namedParameterJdbcTemplate = namedParameterJdbcTemplate;
    }

    public List<Book> findAllOrderBy(String orderBy, int limit, int offset){
        return jdbcTemplate.query(BUILD_QUERY_SELECT_SEARCH(orderBy), new BookRowMapper(),
                limit, offset);
    }

    public List<Book> findAllOrderByWithKeyword(String keyword, String orderBy, int limit, int offset){
        String formattedKeyword = '%' + keyword.trim() + '%';

        return namedParameterJdbcTemplate.query(BUILD_QUERY_SELECT_SEARCH_WITH_KEYWORD(orderBy),
        new MapSqlParameterSource()
                .addValue("keyword", formattedKeyword)
                .addValue("limit", limit)
                .addValue("offset", offset),
        new BookRowMapper());
    }

    public Book findById(String id){
        try {
            return jdbcTemplate.queryForObject(SQL_SELECT_BY_ID, new BookRowMapper(), id);
        }
        catch(EmptyResultDataAccessException e){
            return null;
        }
    }

    /**
     * @param book id field not required, will be generated by method
     */
    public Book save(Book book){
        String UUIDstr = UUID.randomUUID().toString();

        jdbcTemplate.update(SQL_INSERT_BOOK,
                UUIDstr,
                book.getTitle(),
                book.getDescription(),
                book.getISBN(),
                book.getLanguage(),
                book.getPrice(),
                book.getStockQuantity(),
                book.getAuthors(),
                book.getCoverUrl(),
                book.getPubYear(),
                book.getPubMonth(),
                book.getPubDay()
                );

        return findById(UUIDstr);
    }
}
