spring:
    application:
        name: BabelPages

    datasource:
        url: jdbc:mysql://localhost:3306/babelpages_db
        username: joao
        password: ultrapassword
        driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
        enabled: true
        baseline-on-migrate: true

    devtools:
        restart:
            enabled: false

server:
    servlet:
       context-path: /babelpages/api/
    port: 8080
