spring:
    application:
        name: BabelPages

    datasource:
        url: jdbc:mysql://localhost:3306/babelpages_db?sessionVariables=sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
        username: joao
        password: ultrapassword
        driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
        enabled: true
        baseline-on-migrate: true

    devtools:
        restart:
            enabled: false

server:
    servlet:
       context-path: /babelpages/api/
    port: 8080
