insert into tags (name, type) values ("Horror", "GENRE"),
                                     ("Science Fiction", "GENRE"),
                                     ("Mystery", "GENRE"),
                                     ("Biography", "GENRE"),
                                     ("Fantasy", "GENRE"),
                                     ("Drama", "GENRE"),
                                     ("History", "GENRE"),
                                     ("Cooking", "GENRE"),
                                     ("Romance", "GENRE"),
                                     ("Humor", "GENRE");

insert into tags (name, type) values ("Short", "DESC"),
                                     ("Plot twist", "DESC"),
                                     ("Scary", "DESC"),
                                     ("Religious Themes", "DESC"),
                                     ("Mature Content", "DESC"),
                                     ("Abuse", "DESC"),
                                     ("Space", "DESC"),
                                     ("Text Book", "DESC"),
                                     ("Funny", "DESC"),
                                     ("Fascinating", "DESC"),
                                     ("Hard read", "DESC"),
                                     ("Easy read", "DESC"),
                                     ("Violence", "DESC"),
                                     ("Gore", "DESC"),
                                     ("Complex", "DESC");
