insert into tags (name, type) values
                                  ("Adventure", "GENRE"),
                                  ("Romance", "GENRE"),
                                  ("Science Fiction", "GENRE"),
                                  ("Fantasy", "GENRE"),
                                  ("Mystery", "GENRE"),
                                  ("Thriller", "GENRE"),
                                  ("Horror", "GENRE"),
                                  ("Historical", "GENRE"),
                                  ("Biography", "GENRE"),
                                  ("Memoir", "GENRE"),
                                  ("Self-Help", "GENRE"),
                                  ("Health", "GENRE"),
                                  ("Travel", "GENRE"),
                                  ("Cooking", "GENRE"),
                                  ("Art", "GENRE"),
                                  ("Photography", "GENRE"),
                                  ("Music", "GENRE"),
                                  ("Business", "GENRE"),
                                  ("Finance", "GENRE"),
                                  ("Technology", "GENRE"),
                                  ("Education", "GENRE"),
                                  ("Psychology", "GENRE"),
                                  ("Religion", "GENRE"),
                                  ("Spirituality", "GENRE"),
                                  ("Philosophy", "GENRE"),
                                  ("Science", "GENRE"),
                                  ("Nature", "GENRE"),
                                  ("Politics", "GENRE"),
                                  ("Social Issues", "GENRE"),
                                  ("Culture", "GENRE"),
                                  ("Humor", "GENRE"),
                                  ("Poetry", "GENRE"),
                                  ("Short Stories", "GENRE"),
                                  ("Drama", "GENRE"),
                                  ("Crime", "GENRE"),
                                  ("Graphic Novels", "GENRE"),
                                  ("Comics", "GENRE"),
                                  ("LGBTQ+", "GENRE"),
                                  ("Women's Fiction", "GENRE"),
                                  ("Historical Fiction", "GENRE"),
                                  ("Young Adult", "GENRE"),
                                  ("Children's Books", "GENRE"),
                                  ("Classic Literature", "GENRE"),
                                  ("Contemporary Fiction", "GENRE"),
                                  ("Literary Fiction", "GENRE"),
                                  ("Urban Fantasy", "GENRE"),
                                  ("Epic Fantasy", "GENRE"),
                                  ("Paranormal", "GENRE"),
                                  ("Supernatural", "GENRE"),
                                  ("Dystopian", "GENRE"),
                                  ("Post-Apocalyptic", "GENRE"),
                                  ("Time Travel", "GENRE"),
                                  ("Space Opera", "GENRE"),
                                  ("Military Fiction", "GENRE"),
                                  ("Spy Fiction", "GENRE"),
                                  ("Detective", "GENRE"),
                                  ("Cozy Mystery", "GENRE"),
                                  ("Psychological Thriller", "GENRE"),
                                  ("Legal Thriller", "GENRE"),
                                  ("Medical Thriller", "GENRE"),
                                  ("Espionage", "GENRE"),
                                  ("Domestic Thriller", "GENRE"),
                                  ("Gothic", "GENRE"),
                                  ("Magic Realism", "GENRE"),
                                  ("Religious Fiction", "GENRE"),
                                  ("Inspirational", "GENRE"),
                                  ("Chick Lit", "GENRE"),
                                  ("New Adult", "GENRE"),
                                  ("Historical Romance", "GENRE"),
                                  ("Contemporary Romance", "GENRE"),
                                  ("Paranormal Romance", "GENRE"),
                                  ("Romantic Suspense", "GENRE"),
                                  ("Western Romance", "GENRE"),
                                  ("Fantasy Romance", "GENRE"),
                                  ("Science Fiction Romance", "GENRE"),
                                  ("Manga", "GENRE"),
                                  ("Light Novels", "GENRE"),
                                  ("Asian Fiction", "GENRE"),
                                  ("African Fiction", "GENRE"),
                                  ("Middle Eastern Fiction", "GENRE"),
                                  ("Latin American Fiction", "GENRE"),
                                  ("Caribbean Fiction", "GENRE"),
                                  ("Multicultural Fiction", "GENRE"),
                                  ("Family Saga", "GENRE"),
                                  ("True Crime", "GENRE"),
                                  ("Forensics", "GENRE"),
                                  ("Psychiatry", "GENRE"),
                                  ("Counseling", "GENRE"),
                                  ("Therapy", "GENRE"),
                                  ("Mindfulness", "GENRE"),
                                  ("Meditation", "GENRE"),
                                  ("Exercise", "GENRE"),
                                  ("Fitness", "GENRE"),
                                  ("Nutrition", "GENRE"),
                                  ("Parenting", "GENRE"),
                                  ("Relationships", "GENRE"),
                                  ("Mental Health", "GENRE"),
                                  ("Addiction", "GENRE"),
                                  ("Survival", "GENRE"),
                                  ("War", "GENRE"),
                                  ("Ancient History", "GENRE"),
                                  ("Archaeology", "GENRE"),
                                  ("Sociology", "GENRE"),
                                  ("Gender Studies", "GENRE"),
                                  ("Cultural Studies", "GENRE"),
                                  ("Environmental Science", "GENRE"),
                                  ("Astronomy", "GENRE"),
                                  ("Physics", "GENRE"),
                                  ("Chemistry", "GENRE"),
                                  ("Biology", "GENRE"),
                                  ("Geology", "GENRE"),
                                  ("Mathematics", "GENRE"),
                                  ("Engineering", "GENRE"),
                                  ("Robotics", "GENRE"),
                                  ("Computer Science", "GENRE"),
                                  ("Programming", "GENRE"),
                                  ("Software Development", "GENRE"),
                                  ("Game Development", "GENRE"),
                                  ("Cybersecurity", "GENRE"),
                                  ("Artificial Intelligence", "GENRE"),
                                  ("Blockchain", "GENRE"),
                                  ("Cryptocurrency", "GENRE"),
                                  ("Space Exploration", "GENRE"),
                                  ("Aviation", "GENRE"),
                                  ("Marketing", "GENRE"),
                                  ("Entrepreneurship", "GENRE"),
                                  ("Leadership", "GENRE"),
                                  ("Management", "GENRE"),
                                  ("Personal Finance", "GENRE"),
                                  ("Economics", "GENRE"),
                                  ("Law", "GENRE"),
                                  ("Political Science", "GENRE"),
                                  ("Public Policy", "GENRE"),
                                  ("Government", "GENRE"),
                                  ("Social Justice", "GENRE"),
                                  ("Community Development", "GENRE"),
                                  ("Architecture", "GENRE"),
                                  ("Interior Design", "GENRE"),
                                  ("Historic Preservation", "GENRE"),
                                  ("Art History", "GENRE"),
                                  ("Performing Arts", "GENRE"),
                                  ("Theater", "GENRE"),
                                  ("Dance", "GENRE"),
                                  ("Film Studies", "GENRE"),
                                  ("Television", "GENRE"),
                                  ("Screenwriting", "GENRE"),
                                  ("Creative Writing", "GENRE"),
                                  ("Journalism", "GENRE"),
                                  ("Broadcasting", "GENRE"),
                                  ("Painting", "GENRE"),
                                  ("Drawing", "GENRE"),
                                  ("Sculpture", "GENRE"),
                                  ("Crafts", "GENRE"),
                                  ("Fashion", "GENRE"),
                                  ("Design", "GENRE"),
                                  ("Graphic Design", "GENRE"),
                                  ("Animation", "GENRE"),
                                  ("Game Design", "GENRE"),
                                  ("Music Theory", "GENRE"),
                                  ("Music Performance", "GENRE"),
                                  ("Instrumental Music", "GENRE"),
                                  ("Vocal Music", "GENRE"),
                                  ("Choir", "GENRE"),
                                  ("Orchestra", "GENRE"),
                                  ("Band", "GENRE"),
                                  ("Jazz", "GENRE"),
                                  ("Rock", "GENRE"),
                                  ("Pop", "GENRE"),
                                  ("Hip Hop", "GENRE"),
                                  ("Electronic Music", "GENRE"),
                                  ("World Music", "GENRE"),
                                  ("Classical Music", "GENRE"),
                                  ("Music History", "GENRE"),
                                  ("Music Business", "GENRE"),
                                  ("Music Production", "GENRE"),
                                  ("Sound Engineering", "GENRE"),
                                  ("Recording Techniques", "GENRE"),
                                  ("Live Sound", "GENRE"),
                                  ("Music Technology", "GENRE"),
                                  ("DJing", "GENRE"),
                                  ("Songwriting", "GENRE"),
                                  ("Lyric Writing", "GENRE"),
                                  ("Film Music", "GENRE"),
                                  ("Music Education", "GENRE"),
                                  ("Ethnomusicology", "GENRE"),
                                  ("Music Psychology", "GENRE"),
                                  ("Sound Studies", "GENRE"),
                                  ("Acoustics", "GENRE"),
                                  ("Genealogy", "GENRE"),
                                  ("Archives", "GENRE");


insert into tags (name, type) values ("Short", "DESC"),
                                     ("Plot twist", "DESC"),
                                     ("Scary", "DESC"),
                                     ("Religious Themes", "DESC"),
                                     ("Mature Content", "DESC"),
                                     ("Abuse", "DESC"),
                                     ("Space", "DESC"),
                                     ("Text Book", "DESC"),
                                     ("Funny", "DESC"),
                                     ("Fascinating", "DESC"),
                                     ("Hard read", "DESC"),
                                     ("Easy read", "DESC"),
                                     ("Violence", "DESC"),
                                     ("Gore", "DESC"),
                                     ("Complex", "DESC");
