ALTER TABLE tags DROP PRIMARY KEY ;
ALTER TABLE tags MODIFY id INT AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE tags ADD CONSTRAINT tag_type_check CHECK (type IN ("DESC", "GENRE"));

ALTER TABLE tags MODIFY type CHAR(5) NOT NULL;